version: '3'
services:
  bitcoin_mainnet:
    build: dockers/bitcoin/
    environment:
      - BTC_CONF=/root/bitcoin.conf
    volumes:
      - ./data/bitcoin_mainnet:/data

  bitcoin_testnet:
    build: dockers/bitcoin/
    environment:
      - BTC_CONF=/root/testnet.conf
    volumes:
      - ./data/bitcoin_testnet:/data

  eclair_testnet:
    image: acinq/eclair
    restart: unless-stopped
    volumes:
      - ./data/eclair_testnet:/data
    depends_on:
      - bitcoin_testnet
    entrypoint: 'java -Declair.printToConsole -Declair.bitcoind.rpcuser=kek -Declair.bitcoind.rpcpassword=kek -Declair.bitcoind.host=crypto_bitcoin_testnet_1 -Declair.bitcoind.rpcport=8332 -Declair.bitcoind.zmq="tcp://crypto_bitcoin_testnet_1:29000" -Declair.api.binding-ip=0.0.0.0 -Declair.datadir=/data -jar eclair-node.jar'

  rsk_mainnet:
    build: dockers/rsk/
    environment:
      - RSK_CONF=/etc/rsk/mainnet.conf
    volumes:
      - ./data/rsk_mainnet:/var/lib/rsk/database/mainnet

  rsk_testnet:
    build: dockers/rsk/
    environment:
      - RSK_CONF=/etc/rsk/testnet.conf
    volumes:
      - ./data/rsk_testnet:/var/lib/rsk/database/testnet

  rsk_mainnet_explorer:
    build: dockers/explorer/
    environment:
      - MONGO_URI=mongodb://crypto_mongodb_1/blockDB
      - EXPLORER_CONFIG=/usr/src/explorer/mainnet.json
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - rsk_mainnet
      - mongodb

  rsk_testnet_explorer:
    build: dockers/explorer/
    environment:
      - MONGO_URI=mongodb://crypto_mongodb_1/blockDBTestnet
      - EXPLORER_CONFIG=/usr/src/explorer/testnet.json
    ports:
      - "3002:3000"
    restart: unless-stopped
    depends_on:
      - rsk_testnet
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  ganache:
    image: trufflesuite/ganache-cli:latest

  cli:
    build: dockers/cli/
    ports:
      - "3000:8080"
    depends_on:
      - rsk_mainnet
      - rsk_testnet
      - ganache
